export const TRIP_STATUS_OPEN = 0
export const TRIP_STATUS_AWAITING_DRIVER = 2
export const TRIP_STATUS_DRIVER_PATH = 3
export const TRIP_STATUS_FINISHED = 4
export const TRIP_STATUS_STARTED = 5
export const TRIP_STATUS_CANCELED = 6
export const TRIP_STATUS_DRIVER_CANCELED = 7
